# This is a basic workflow to help you get started with Actions
# test 2
name: Deploy to GAE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
      # create env file
      - name: Create .env.local
        run: printenv > /home/runner/work/goblog-client/goblog-client/.env.local

      # checking env file
      - name: Check .env.local
        run: cat /home/runner/work/goblog-client/goblog-client/.env.local

      # checkout the latest codebase
      - name: Checkout
        uses: actions/checkout@v4

      # deploy the code
      - name: Deploy to App Engine
        id: deploy
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_CREDENTIALS }}

      # test to ensure the app had been deployed successfully
      - name: Test
        run: curl "${{ steps.deploy.outputs.url }}"