#name: Build and Deploy to GAE
#
#on:
#  push:
#    branches: [ "main" ]
#
#jobs:
#  setup-build-publish-deploy:
#    name: Setup, Build, Publish, and Deploy
#    runs-on: ubuntu-latest
#    environment: production
#
#    permissions:
#      contents: 'read'
#      id-token: 'write'
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
#
#      # Configure Workload Identity Federation and generate an access token.
#      - id: 'auth'
#        name: 'Authenticate to Google Cloud'
#        uses: 'google-github-actions/auth@v0'
#        with:
#          token_format: 'access_token'
#          workload_identity_provider: '${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
#          service_account: ${{ secrets.SERVICE_ACCOUNT }}
#
#      - name: 'Deploy to App Engine'
#        id: 'deploy'
#        uses: 'google-github-actions/deploy-appengine@v2'

# This is a basic workflow to help you get started with Actions
# test 2
name: Deploy to GAE

# Controls when the workflow will run
on:
  # Triggers the workflow on push request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: 'Deploy to App Engine'
        id: 'deploy'
#        uses: 'google-github-actions/deploy-appengine@v2'
        run: 'gcloud auth login'

      - name: Test
        run: curl "${{ steps.deploy.outputs.url }}"
